export const TABLE_HEAD = [
  "Enquire No",
  "Student Name",
  "Mobile No",
  "Course",
  "Enquire Source",
  "Enquire Date",
  "Assign to",
  "Enquire Status",
  "Actions",
];

// Demo data
export const TABLE_ROWS = [
  {
    "Enquire No": "ENQ123",
    "Student Name": "John Doe",
    "Mobile No": "1234567890",
    Course: "Mathematics",
    "Enquire Source": "Advertisement",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher A",
    "Enquire Status": "Pending",
  },
  {
    "Enquire No": "ENQ124",
    "Student Name": "Alice Smith",
    "Mobile No": "9876543210",
    Course: "English Literature",
    "Enquire Source": "Website",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher B",
    "Enquire Status": "Follow-up",
  },
  {
    "Enquire No": "ENQ125",
    "Student Name": "Michael Johnson",
    "Mobile No": "5551234567",
    Course: "Physics",
    "Enquire Source": "Referral",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher C",
    "Enquire Status": "Enrolled",
  },
  {
    "Enquire No": "ENQ126",
    "Student Name": "Emily Davis",
    "Mobile No": "1112223333",
    Course: "Chemistry",
    "Enquire Source": "Social Media",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher D",
    "Enquire Status": "Pending",
  },
  {
    "Enquire No": "ENQ127",
    "Student Name": "Robert Brown",
    "Mobile No": "4445556666",
    Course: "Biology",
    "Enquire Source": "Advertisement",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher E",
    "Enquire Status": "Follow-up",
  },
  {
    "Enquire No": "ENQ128",
    "Student Name": "Emma Wilson",
    "Mobile No": "7778889999",
    Course: "History",
    "Enquire Source": "Website",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher F",
    "Enquire Status": "Enrolled",
  },
  {
    "Enquire No": "ENQ129",
    "Student Name": "William Taylor",
    "Mobile No": "2223334444",
    Course: "Geography",
    "Enquire Source": "Referral",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher G",
    "Enquire Status": "Pending",
  },
  {
    "Enquire No": "ENQ130",
    "Student Name": "Olivia Martinez",
    "Mobile No": "6667778888",
    Course: "Computer Science",
    "Enquire Source": "Social Media",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher H",
    "Enquire Status": "Follow-up",
  },
  {
    "Enquire No": "ENQ131",
    "Student Name": "James Anderson",
    "Mobile No": "8889990000",
    Course: "Economics",
    "Enquire Source": "Advertisement",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher I",
    "Enquire Status": "Enrolled",
  },
  {
    "Enquire No": "ENQ132",
    "Student Name": "Sophia Hernandez",
    "Mobile No": "3334445555",
    Course: "Art",
    "Enquire Source": "Website",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher J",
    "Enquire Status": "Pending",
  },
  {
    "Enquire No": "ENQ133",
    "Student Name": "Daniel Rodriguez",
    "Mobile No": "9990001111",
    Course: "Music",
    "Enquire Source": "Referral",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher K",
    "Enquire Status": "Follow-up",
  },
  {
    "Enquire No": "ENQ134",
    "Student Name": "Isabella Lopez",
    "Mobile No": "4445556666",
    Course: "Physical Education",
    "Enquire Source": "Social Media",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher L",
    "Enquire Status": "Enrolled",
  },
  {
    "Enquire No": "ENQ135",
    "Student Name": "Mason Moore",
    "Mobile No": "1112223333",
    Course: "Psychology",
    "Enquire Source": "Advertisement",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher M",
    "Enquire Status": "Pending",
  },
  {
    "Enquire No": "ENQ136",
    "Student Name": "Ava Gonzalez",
    "Mobile No": "7778889999",
    Course: "Sociology",
    "Enquire Source": "Website",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher N",
    "Enquire Status": "Follow-up",
  },
  {
    "Enquire No": "ENQ137",
    "Student Name": "Liam Perez",
    "Mobile No": "2223334444",
    Course: "Philosophy",
    "Enquire Source": "Referral",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher O",
    "Enquire Status": "Enrolled",
  },
  {
    "Enquire No": "ENQ138",
    "Student Name": "Charlotte Carter",
    "Mobile No": "6667778888",
    Course: "Political Science",
    "Enquire Source": "Social Media",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher P",
    "Enquire Status": "Pending",
  },
  {
    "Enquire No": "ENQ139",
    "Student Name": "Noah King",
    "Mobile No": "8889990000",
    Course: "Anthropology",
    "Enquire Source": "Advertisement",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher Q",
    "Enquire Status": "Follow-up",
  },
  {
    "Enquire No": "ENQ140",
    "Student Name": "Ella Wright",
    "Mobile No": "3334445555",
    Course: "Languages",
    "Enquire Source": "Website",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher R",
    "Enquire Status": "Enrolled",
  },
  {
    "Enquire No": "ENQ141",
    "Student Name": "Logan Lee",
    "Mobile No": "9990001111",
    Course: "Engineering",
    "Enquire Source": "Referral",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher S",
    "Enquire Status": "Pending",
  },
  {
    "Enquire No": "ENQ142",
    "Student Name": "Amelia Green",
    "Mobile No": "4445556666",
    Course: "Medicine",
    "Enquire Source": "Social Media",
    "Enquire Date": "2023/01/03",
    "Assign to": "Teacher T",
    "Enquire Status": "Follow-up",
  },
];
